version: '3.9'

services:
  mongors1n1:
    image: 'mongo:5.0.3'
    container_name: cs_mongodb
    expose:
      - ${MONGO_PORT}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  cs_fastapi:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: cs_fastapi
    restart: always
    env_file:
      - ./.env
    expose:
      - ${SERVICE_PORT}
    logging:
      options:
        max-size: 50m
    depends_on:
      - ${MONGO_HOST}

  cs_redis:
    image: 'redis:6.2.6'
    container_name: cs_redis
    expose:
      - ${REDIS_PORT}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  cs_tests:
    container_name: cs_tests
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: tests/Dockerfile
    command: >
      sh -c "pytest /app/tests -s -v -p no:warnings && flake8 ."
    depends_on:
      - cs_fastapi
    profiles:
      - testing

  nginx:
    container_name: cs_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - ${NGINX_PORT}:8080
    env_file:
      - ./.env
    depends_on:
      - cs_fastapi