@startuml

:Проблема;
note right
  Каждый запрос в сервис UGC должен быть
  соотнесен с пользователем, который его сделал.
  Можно реализовать проверку токена на уровне
  сервиса, либо убрать UGC за Async API, чтобы
  принимать только валидные запросы.
end note

:Решение;
note right
  Несмотря на некоторое дублирование функций,
  оптимальным представляется решение, при котором
  сервис UGC независим от Async API и самостоятельно
  проверяет авторизационный токен в заголовке запроса.
end note

:Люди принявшие решение;
note right
  Дмитрий Кузнецов, Вера Герасимович, Сергей Сименштейн
end note

:Комментарии;
note right
  Недостатком решения может служить необходимость
  вносить изменения в оба сервиса UGC и Async API
  в случае смены формата токена. Преимуществом
  является меньшая связанность компонентов.
end note

:Альтернативы;
note right
  Альтернативным вариантом является реализация
  решения при котором UGC имеет дополнительные
  ручки для принятия «внутренних» запросов
  без авторизации.
end note

:2021.12.14;

@enduml
