version: '3'

services:
  movies-api-ugc:
    image: movies-api-ugc
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-api-ugc
    command: >
      python main.py
    volumes:
      - "./src:/code"
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - ugc

networks:
  ugc:
    name: ugc
    driver: bridge
